int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int is_palindrome(char *s);
int is_prime_number(int n);
int num(int n, int i);
int num2(int n, int i, int count);
int str(char *s, int size);
int wildcmp(char *s1, char *s2);
